---
title: "Final_HW"
author: "Ivanova Ekaterina"
date: '2022-11-16'
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE, message=FALSE, results='hide', warning=FALSE}
library(dplyr)
library(tibble)
library(skimr)
library(ggplot2)
library(dplyr)
library(readxl)
library(stringr)
library(tidyr)
library(flextable)

```



```{r, echo=FALSE, message=FALSE, warning=FALSE}

data_raw <- read.csv("data_excel - data.csv", encoding = "UTF-8", dec = ",")



statistics <- list(
      `Количество субъектов` = ~length(.x),
      `Количество (есть данные)` = ~sum(!is.na(.x)),
      `Нет данных` = ~sum(is.na(.x)),
      `Ср. знач.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", mean(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Станд. отклон.` = ~ifelse(sum(!is.na(.x)) < 3, "Н/П*", sd(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `95% ДИ для среднего` = ~sd(.x, na.rm = TRUE) %>% round(2) %>% as.character(),
      `мин. - макс.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(min(.x, na.rm = TRUE) %>% round(2), " - ", max(.x, na.rm = TRUE) %>% round(2))),
      `Медиана` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", median(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Q1 - Q3` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(quantile(.x, 0.25, na.rm = TRUE) %>% round(2), " - ", quantile(.x, 0.75, na.rm = TRUE) %>% round(2)))
)



test <- data_raw %>%
  select(`Группа`, where(is.numeric)) %>%
  group_by(`Группа`) %>%
  summarise(across(where(is.numeric), statistics)) 



  
test_res <- test %>% mutate(across(everything(), as.character)) %>% 
  pivot_longer(!`Группа`) %>%
  mutate(name = paste(name, "E1", sep = "_")) %>%
  separate(name, into  = c("Переменная","Визит1" ,"Статистика", "Визит"), sep = "_") %>%
  mutate(`Stat` = if_else(`Статистика` == "E1",`Визит1`, `Статистика`)) %>%
  mutate(`Visit` = if_else(`Статистика` == "E1"| `Визит1` == "E1","E1", "E2")) %>%
  mutate(`Визит1` = NULL, `Статистика` = NULL, `Визит`  = NULL) %>%
  rename("Значение" = value, "Статистика" = Stat, "Визит" = Visit) %>%
  relocate(`Группа`, `Переменная`, `Визит`, `Статистика`, `Значение`) 


  
test_res %>%
  flextable() %>%
  theme_box() %>%
  merge_v(c("Переменная", "Визит","Группа")) %>%
  set_caption("Описательная статистика количественных переменных") %>%
  width(width = 1.2)



res1 <- round(t.test(`Базофилы_E1` ~ `Группа`, data_raw)$p.value, 4)
res2 <- round(t.test(`Базофилы_E2` ~ `Группа`, data_raw)$p.value, 4)
res3 <- round(t.test(`Эозинофилы_E1` ~ `Группа`, data_raw)$p.value, 4)
res4 <- round(t.test(`Эозинофилы_E2` ~ `Группа`, data_raw)$p.value, 4)
res5 <- round(t.test(`Гемоглобин_E1` ~ `Группа`, data_raw)$p.value, 4)
res6 <- round(t.test(`Гемоглобин_E2` ~ `Группа`, data_raw)$p.value, 4)
res7 <- round(t.test(`Эритроциты_E1` ~ `Группа`, data_raw)$p.value, 4)
res8 <- round(t.test(`Эритроциты_E2` ~ `Группа`, data_raw)$p.value, 4)


params <- c("Базофилы_E1", "Базофилы_E2", "Эозинофилы_E1", "Эозинофилы_E2", "Гемоглобин_E1", "Гемоглобин_E2",
            "Эритроциты_E1", "Эритроциты_E2")
pval_res <- c(res1, res2, res3, res4, res5, res6, res7, res8)


tibble("Параметр" = params, "p-value" = pval_res)%>%
  flextable() %>%
  theme_box() %>%
  set_caption("Результаты сравнения средних значений параметров") %>%
  width(width = 1.2)




data_raw %>%
  select(`Группа`, where(is.character)) %>%
  mutate(`Группа.крови` = `Группа.крови` %>% as.character %>% replace_na("Нет данных") %>% as.character()) %>%
  count(`Группа`, `Группа.крови`) %>%
  group_by(`Группа`) %>%
  mutate(`Процент по группе` = (n/sum(n)) %>% round(4) %>% `*` (100) %>% str_c("%")) %>%
  ungroup() %>%
  mutate(`Процент по выборке` = (n/sum(n)) %>% round(4) %>% `*` (100) %>% str_c("%")) %>%
  flextable() %>%
  theme_box() %>%
  merge_v("Группа") %>%
  set_caption("Сводная таблица данных о группе крови пациентов") %>%
  width(width = 1.2) 
                                                                              
  
  


data_raw %>%
  select(`Группа`, where(is.character)) %>%
  count(`Группа`, `Пол`) %>%
  group_by(`Группа`) %>%
  mutate(`Процент по группе` = (n/sum(n)) %>% round(4) %>% `*` (100) %>% str_c("%")) %>%
  ungroup() %>%
  mutate(`Процент по выборке` = (n/sum(n)) %>% round(4) %>% `*` (100) %>% str_c("%")) %>%
  flextable() %>%
  theme_box() %>%
  merge_v("Группа") %>%
  set_caption("Данные о гендерной структуре выборки") %>%
  width(width = 1.2) 
                      



```


